POST http://localhost:4000/courses HTTP/1.1
Content-Type: application/json

{
	"name": "Saumon grillé",
	"image": "img/food/foodiesfeed.com_grilled-salmon-cubes-with-vegetables (Small).jpg",
	"price": 2000
}

###
GET http://localhost:4000/courses

###
GET http://localhost:4000/courses/id

###
DELETE http://localhost:4000/courses/id

###
PATCH http://localhost:4000/courses/id
Content-Type: application/json

{
	"price": 2550
}

###
# GET USERS
GET http://localhost:4000/users

###
# GET USER By id
GET http://localhost:4000/users/60c8b7b0364fab3b08c0f82c


###
# POST USERS
POST http://localhost:4000/users
Content-Type: application/json

{
	"username": "yacine",
	"email": "yacine@email.com",
	"password": "yacine"
}


###
# PATCH USER
PATCH http://localhost:4000/users/60c8bd67aaf4e22de8449145
Content-Type: application/json

{
	"password": "qwerty"
}

###
# DELETE USER
DELETE http://localhost:4000/users/60c8b7b0364fab3b08c0f82c

###
# Login
POST http://localhost:4000/login
Content-Type: application/json

{
	"email": "yacine@email.com",
	"password": "toto"
}